// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjdT2Fw-qe9NhygeoWLpP6Q4gx-mZQGSc',
    appId: '1:862317854985:web:fb1dd60e10217a755513d8',
    messagingSenderId: '862317854985',
    projectId: 'flafiesta',
    authDomain: 'flafiesta.firebaseapp.com',
    storageBucket: 'flafiesta.firebasestorage.app',
    measurementId: 'G-5QRNRNJCZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK_WyvF_y0jzmjSGMpQip2vZSasPuUWOk',
    appId: '1:862317854985:android:bd0fc8d2682ee8685513d8',
    messagingSenderId: '862317854985',
    projectId: 'flafiesta',
    storageBucket: 'flafiesta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo3tuMn38oii46Bub--N0KpADfjsQPISE',
    appId: '1:862317854985:ios:f0e0cca14134dba65513d8',
    messagingSenderId: '862317854985',
    projectId: 'flafiesta',
    storageBucket: 'flafiesta.firebasestorage.app',
    iosBundleId: 'com.example.flaviesta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo3tuMn38oii46Bub--N0KpADfjsQPISE',
    appId: '1:862317854985:ios:f0e0cca14134dba65513d8',
    messagingSenderId: '862317854985',
    projectId: 'flafiesta',
    storageBucket: 'flafiesta.firebasestorage.app',
    iosBundleId: 'com.example.flaviesta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjdT2Fw-qe9NhygeoWLpP6Q4gx-mZQGSc',
    appId: '1:862317854985:web:b3b4b04059b021345513d8',
    messagingSenderId: '862317854985',
    projectId: 'flafiesta',
    authDomain: 'flafiesta.firebaseapp.com',
    storageBucket: 'flafiesta.firebasestorage.app',
    measurementId: 'G-TVP5F45T9T',
  );
}
